hazleton:
  bams-urls:
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013314/NE2m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013316/SC3m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013318/NC9m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013320/SC2m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013322/NC7f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013324/SC10f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013326/SP4m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013328/SC6m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013330/NC5m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013332/NE4m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013334/SE1m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013336/SC9f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013338/NE3m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013340/NE1m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013342/NC10m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013344/SE4m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013346/SP2m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013348/SE3m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013350/SC4f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013352/NC4m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013354/SC5m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013356/NC2f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013358/HN1f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013360/NC6m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013362/SP3m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013364/SC8m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013366/SE6f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013368/SP1m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013370/NC1m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013372/SE5m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013374/SC1f_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013376/NC8m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013378/SC7m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013380/SE2m_hg19.bam"
  - "ftp.sra.ebi.ac.uk/vol1/run/ERR701/ERR7013382/NC3f_hg19.bam"
